# Site settings
title: taxigy.github.io
author: Rishat Muhametshin
email: rishatmuhametshin@gmail.com
description: No BS.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# social profiles / usernames:
twitter: taxigy
medium: taxigy
github_username:  taxigy
# Build settings
markdown: redcarpet
# Misc
license: CC-BY-CA
